export let PaymnetTermsAndCondition = [
  "Please note that all scholarship concessions will be confirmed only after submission of admission form along with first installment of fee. Any student caught employing unfair practice during the Vertex Educations-Genius Reward Exam (VE-GRE), is subject to immediate expulsion from the examination hall and no refund of the VE-GRE fee already paid shall be made at any cost. A student after qualifying VE GRE and taking admission VERTEX EDUCATIONS (VE) will be bound by the rules & regulation of that centre and in all matters whatsoever the responsibility will be of that centre only.",
  "Note: Any type of scholarship/concession/discount given to the students may attract GST to be paid by the students/parents if levied by the Govt. or as per law at any point of time will be charged/recovered from the student/parents.",
  "",
  "The agreement between you and the VE shall be subject to the following terms and conditions: –",
  "•	The User certifies that he/she is at least 18 (eighteen) years of age or has the consent of a parent or legal guardian.",
  "•	These terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the VE Online Services you agree to be bound by the Terms and Conditions.",
  "•	All prices, unless indicated specially are in Indian Rupees.",
  "•	All prices and availability of products are subject to change without prior notice at the sole discretion of Vertex Educations (VE)..",
  "•	You must use your own credit card. VE will not be liable for any credit card fraud.",
  "•	The User agrees clearly that the use VE all (Online & Offline) Service is at the Users sole risk. VE affiliates, employees, agents, consultants, contracted companies make no warranties of any kind, whether expressed or implied for the service it is providing or as to the results that may be obtained from the use of the Service, or as to the accuracy, reliability or content of any information, service, or merchandise provided through this Service. It is also clearly understood that all warranties, implied or expressed take place between the vendors and the User.",
  "•	Any student enrolled with VE will have to regularly work hard. In case the teacher feel that the student is not working hard, creating indiscipline, or using unfair means in the institute or in classes, irregular in attendance, not responding properly, he/she may be expelled from the institute. The decision of the VE in this regard will be final and binding on the student/parent. No fee or part of the fee will be refunded in such cases.",
  "•	After depositing money towards ‘Registration & Admission’, if a student becomes disinterested in the Institute due to any reason whatsoever and wants to take his/her money back, the Institute will not refund the money deposited towards Registration fee/Admission fee. However, if a student applies for refund before the commencement of course/classes, only admission fee and first instalment of tuition fee will be refunded along with PDCs submitted, if any. The registration/admission fee deposited towards a particular course will not be adjusted against any other course.",
  "•	It is the responsibility of the parents to submit the fee of their ward in time as per schedule given in the admission letter. They should not expect reminders and calls from the centre.",
  "•	If the cheque is bounced for any reason whatsoever, a fine of Rs. 500 will be charged separately from the student along with the fee instalment.",
  "•	It is compulsory/mandatory to provide active e-mail I.D. Mobile No and Whatsapp No. of the student/ father/guardian. The result of tests, important notifications, updates and/or any other information of the Institute will be sent to the student through Call, whatsapp and/or SMS. The Institute shall not be responsible for any information regarding result or anything else not received by the student if he/she has not given his/her e-mail I.D./mobile no. in the Admission form at the time of admission.",
  "•	If any type of mishap occurs in the premises of VE because of situations beyond control or any natural calamity such as earthquake, floods, fire, electric short circuit etc, the institute shall not be responsible in any manner whatsoever.",
  "•	The Examination Centre of any place can be changed as per the requirement/ need of the company without any prior notice to the students/parents.",
  "•	VE reserves the right to use the photograph for publicity in case the student secures position/success in any Engineering/Medical Entrance Exams as well as in Olympiads, NTSE & KVPY or any other national level entrance tests.",
  "•	In case any parent/guardian/student is found misbehaving with any staff member of the Institute, his/her ward can be rusticated and no claim to retain such student will be entertained. The decision of the Directors will be final and binding on the student and parents/guardian.",
  "•	If at any point of time, the Govt. further increases GST or levy any other tax, the extra amount of GST or other tax will be borne by the students from the date of enforcement of the act by the Govt.",
  "•	VE reserves the right to make any alteration in its programs/venue/timing and days of classes without any prior notice to anybody. The decision of the Directors will be final & binding on the students and the parents.",
  "•	VE reserve the right to amend any of the terms mentioned above without giving any notice.",
  "",
  "",
  "Disclaimer: I hereby give my consent that even if my mobile number is registered with NDNC, I would like VE or any of its partner institutions, employees, officers, authorized agencies, service partners and representatives to call, message or email me for any matter related to the course, admission, or any other service.",
  "",
  "",
  "",
];
export const PaymentPrivacyData = [
  "Privacy Policy",
  "Welcome to Vertex Educations. We’re glad you want to use the leading streaming service for JEE Main & Advanced. We value the privacy of all of our users and we know you care about your privacy, so we created this Privacy Policy. It explains the information we collect from users and how and when we disclose or use it. By accessing or using this website, you are consenting to collection and use of your information as outlined in this Privacy Policy. When you use this website, you also agree to our Terms of Service.",
  "This Privacy Policy applies to your use of www.vegre.in or third-party sites that link to own website.",
  "1. About Us",
  "2. What information we collect",
  "2.1. Registering with Vertex Educations. When you register on the Vertex Educations Website, we and third parties working with us will collect the following information",
  "•	Name, Father’s Name, Email Id, Mobile Number, Date of Birth, Address, Class Studying, profile photo.",
  "•	Other personal data if you choose to register for a account via third party sites including Facebook and Google, and have provided your personal information on those platforms",
  "•	Data provided by you at enrolment in Courses.",
  "•	Your fee details and payment history.",
  "•	Information provided by you when you correspond with us (including via surveys).",
  "•	If payment is made by means of a card that you do not personally own, the permission of the card owner must always be obtained to make payments using the card. In using the system you confirm that you have such permission.",
  "2.2. Accessing the Website  ",
  "When you access the Website we may use cookies to track, collect, and aggregate information about your use of the Website, including pages you have visited, the specific URLs that brought you to our Website, and links embedded on our Website that you have accessed.  This information may include IP addresses, and any information collected by cookies.  This may also include information such as the time and length of visits to certain pages on our website and page interaction information.",
  "3. How we use your information",
  "3.1. In providing our online services and products to you, we and third parties we work with will collect, store, and use your personal information for the following purposes:",
  "3.2. to manage your Learner account;",
  "3.3. to provide technical support to you;",
  "3.4. to send notifications and updates about Courses you are enrolled on your mail/mobile number;",
  "3.5. to contact you in order to invite you to share your opinions of and experiences with us, and to to publish customer reviews and ratings of our Courses on our Website or on other media channels;",
  "3.6. for marketing purposes, where you provide us with your consent to receive marketing communications, which may include email and/or telephone communications with information, news, and offers of Courses on our Website and third party offers;",
  "3.7. We use cookies to collect information relating to your use of the Website to enable, maintain and improve the functioning of our Website and the quality of our products and services.",
  "",
  "",
  "4. Whom we may share your information with",
  "4.1. For the above purposes, we may share your information with our service providers who provide services such as website/software hosting, data analysis, payment processing, order fulfillment and other services.",
  "4.2. our payment services providers such as Razorpay, Paytm;",
  "4.3 We may share your personal information with our bankers for clearing necessary fees payments. This information shall be strictly up to the legal permissible limit and not exceeding.",
  "4.4. customer relationship management service providers (which allows us, for example, to send personalised email communications to you);",
  "4.5. Any entity to which we are under a duty to disclose or share your information in order to comply with any legal obligation, or in order to enforce or apply our Terms and other legal requirements; or to protect our rights, property, or safety, our users, or others. This includes exchanging information with other companies and organisations for the purposes of fraud protection and credit risk reduction.",

  "",
  "",
  "",
  "5. Storage and Security of Information",
  "5.1. All information is stored on our secure servers. When you register, we will share a password which enables you to access the Online Courses and Content. You are responsible for keeping this password confidential. We ask you not to share this password with anyone.",
  "5.2. In circumstances where your personal information is collected, we use reasonable procedural and digital security measures that are designed to help protect against loss, unauthorized access, disclosure, alteration or destruction of information and data, such as password protection and secure socket layer. Unfortunately, no data transmission or storage system can be guaranteed to be 100% secure. If you have reason to believe the security of your account has been compromised, please immediately notify us in accordance with the “Contact Us” section below.",
  "5.3. Vertex Educations shall not be liable for any failure by the Student or third party making payment of Fees to properly protect data from being seen on their screen by other persons or otherwise obtained by such other persons, during the Online Payment process or in respect of any omission to provide accurate information in the Course of the Online Payment Process.",
  "",
  "",
  "",
  "6. Your Rights",
  "6.1. If you have any privacy-related questions or unresolved problems, you may contact us using the information provided below.",
  "",
  "",
  "",
  "7. Children",
  "We take seriously our legal obligation to protect the privacy of children. Accordingly, we do not knowingly collect or maintain personal information from persons under 13 years of age, and no part of the Website is directed to persons under 13 years of age. If you are under 13 years of age, then please do not use or access the Website at any time or in any manner. We will take appropriate steps to delete any personal information of persons less than 13 years of age.",
  "",
  "",
  "",
  "8. Cookies",
  "The Website uses cookies. Cookies are small files stored on your computer’s hard drive which are used to collect your personal information. You may choose to refuse cookies but, if you do so, some of the functionality of the Website may no longer be available to you.",
  "",
  "",
  "",

  "9. Refund & Cancellation Policy",
  "Vertex Educations do our best to accommodate students’ needs and provide assistance, but students are expected to be sufficiently motivated and committed to the program in which they have enrolled. If a student is dissatisfied, he/she is expected to raise his/her concerns immediately and give us the opportunity to resolve them.",
  "Kindly be informed that, we have a “NO-REFUND” policy. Fees are NON-Refundable once Paid.",
  "10. Contact details If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me.",
  "",
  "",
  "",
  "Vertex Educations Private Limited\
First Floor, AMS park, Behind Hira Panna Jewellers,\
Boring Road Crossing, Patna- 800001.\
",
  "E-mail: info@vertexeducations.com",
  "Call Us: +91 9031011932 | +91 9031011931",
  "",
  "",
  "11. Updating this Privacy Policy",
  "We reserve the right to change or modify our Privacy Policy from time to time by posting a revised Privacy Policy on our site. The “last updated” legend at the top of this page indicates when this Policy was last revised. As an ongoing user of our service, you will be subject to the terms of the then-current Privacy Policy. We ask that you refer to the Privacy Policy on a continuing basis so that you understand our current privacy practices. By submitting a payment through online-payments site you are agreeing to these terms and conditions including any updated changes in terms and conditions from time to time through our website.",
  "",
  "",
];
export const paymentRefund = [
  "Refund /Collection Policy",
  "Vertex Educations do our best to accommodate students’ needs and provide assistance, but students are expected to be sufficiently motivated and committed to the program in which they have enrolled. If a student is dissatisfied, he/she is expected to raise his/her concerns immediately and give us the opportunity to resolve them.",
  "",
  "Kindly be informed that, we have a “NO-REFUND” policy. Fees are NON-Refundable once Paid.",
  "",
];
export const paymentContact = [
  "Contact Us",
  "",
  "Vertex Educations Private Limited",
  "First Floor, AMS park, Behind Hira Panna Jewellers,\
Boring Road Crossing, Patna- 800001.\
",
  "E-mail: info@vertexeducations.com",
  "Call Us: +91 9031011932 | +91 9031011931",
  "",

  // "1.      Cash rewards, scholarships, hostel fee benefits (at patna) will be decided on the basis of performance in the VE-GRE Exam and are subjected to score above minimum cut-off marks in each subject.",
  // "2.      In case of more than one participating student securing equal aggregate marks in the VE-GRE, better Rank shall be given by comparing scores individually in the subjects in the order of decreasing priority: Mathematics, Science (P, C, B) & Mental Ability for Class 7 to 10 and Mathematics/Biology, Physics, Chemistry for Class 11. If individual scores in all the subjects are also equal, then the youngest student shall be given better rank.",
  // "3.      Students will be entitled for assured cash rewards on the basis of their performance in VE-GRE irrespective of their decision to enroll for Vertex Educations Classroom program or not. Students eligible for cash reward (on admission) can avail it at the time of admission through waiver of fee amount equivalent to the reward amount. ",
  // "4.      To get the scholarships and hostel fee benefits (at patna) related to VE-GRE, one has to enroll for any of the classroom programs of Vertex Educations.",
  // "5.      The assured cash reward shall be given to the eligible students on attending Felicitation Function to be organised by Vertex Educations. No Reward shall be handed over in person to any of student's relative/guardian or his/her representative in any case. The venue and date will be announced through SMS and telephone calls. You can also view it on our website www.vertexeducations.com after VE-GRE results.  ",
  // "6.      Students enrolling with Vertex Educations through VE-GRE can avail another golden opportunity of fetching additional cash rewards by qualifying in JEE MAIN, JEE ADVANCED, NEET-UG.",
  // "(a)    The rewards will be applicable for JEE MAIN / JEE ADVANCED /  NEET-UG  Rank.",
  // "(b)    The rewards for regular classroom program students will be given, if a student maintains 80% attendance in the Classes & Tests.",
  // "(c)    Only one reward shall be given to a student. Any student claiming this reward need to be present in the Felicitation function to be organized by Vertex Educations with selection letter showing the rank. After Felicitation function no reward will be given.",
  // "(d)    Reward will be given to top 20 students enrolled with Vertex Educations in each of JEE MAIN, JEE ADVANCED, NEET-UG each year.",
  // "7.      Assured Cash Rewards will be paid to Students through a crossed cheque and shall be in favour of the Student/ Student's parent only.",
  // "8.      Hostel fee benefits (at patna) can be availed only by those students who resides at Youn Genius Campus Hostel of Vertex Educations at Patna (till seats available). Hostel benefits as per performance in VE-GRE will be adjusted against this mentioned cost. Student will have to bear the difference between monthly charge of hostel & hostel fee benefits. If a student is transferred to Normal Batch due to non-performance, he/she will not be eligible for Hostel Fee waiver",
  // "9.      The final discretion of Cash rewards, scholarships for Vertex Educations classroom programs, hostel fee benefits in each case will remain with Vertex Educations management and this decision will be final and binding on the candidate.",
  // "10.  A student will have to produce required documents [VE-GRE Admit Card & Aadhaar Card] to claim Cash rewards, scholarships for Vertex Educations classroom programs, hostel fee benefits (as directed by Vertex Educations).",
  // "11.   Vertex Educations reserves the right to change/ cancel any Test Center without any prior notice.",
  // "12.   FOR STUDENTS TAKING ADMISSION IN “GROUND ZERO / MEDICAL GROUND ZERO” COURSE THROUGH VE-GRE",
  // "         The cash reward on admission amount offered is Rs. 2,70000. Out of this, Rs. 70,000 will be adjusted at the time of admission. The remaining amount of Rs. 200000 will be awarded to the student in equal installments. To avail this amount, student's average score quarterly in internal tests should be 80% in JEE ADV. pattern test & 85% in JEE MAIN pattern test (Engineering Stream) / 90% in NEET-UG pattern test (Medical Stream).  ",
  // "Student will be eligible for cash reward on admission amount of Rs. 100000 in equal installments, if student's average score quarterly in internal tests is 75% in JEE ADV. pattern test & 85% in JEE MAIN pattern test (Engineering Stream) / 85% in NEET-UG pattern test (Medical Stream).",
  // "Student will be eligible for cash reward on admission amount of Rs. 50000 in equal installments, if student's average score quarterly in internal tests is 70% in JEE ADV. pattern test & 80% in JEE MAIN pattern test (Engineering Stream) / 80% in NEET-UG pattern test (Medical Stream).",
  // "13.   FOR STUDENTS TAKING ADMISSION IN “INFANT STEP” COURSE THROUGH VE-GRE",
  // "Student can take admission for any of the following classroom programs at fee of the Academic Session 2022-23.",
  // "•    1 Yr. (Infant Step Course)",
  // "•    7 Yr. (Infant Step + Prep Step+ First Step + Genesis + Catapult + Ground Zero Course)",
  // "The cash reward on admission amount offered is Rs. 2,75000. Out of this, Rs. 30,000 will be adjusted at the time of admission. The remaining amount of Rs. 245000 will be awarded to the student in equal installments.",
  // "Student will be eligible for cash reward on admission amount of Rs. 45000 in equal installments, if student's average score quarterly in internal tests (during class 6, 7, 8, 9 & 10) is 80%.",
  // "Student will be eligible for cash reward on admission amount of Rs. 200000 in equal installments (during class 11 & 12) as mentioned in point no. 12.",
  // "VE-GRE Selection Letter will be distributed in the career counseling Seminar conducted at various cities (Test Centres of VE-GRE). The date, time & venue of Seminar will be displayed on our website and will be communicated to the students on their registered mobile number by call and SMS. In the Career Counseling Seminar, you will be given important tips and tricks on how to prepare for the Competitive Exams along with your School studies and how to crack Competitive Exams with a good rank along with a good score in Board / School Exams. If for any reason, Govt. doesn’t allows for Educational meeting/Seminar then Online Webinar will be conducted. ",
  // "To avail Cash reward on admission, Scholarship for Vertex Educations Classroom Program and Hostel Fee Benefits student has to Enroll on or before the date mentioned in the VE-GRE Selection Letter given to the students",
  // "         In case Student approaches us to take admission after the mentioned date, then he/she has to pay a late fee as mentioned in the Selection Letter.",
  // ".   Students presently studying in Class 11th and already Enrolled in Vertex Educations in 2 year Regular Classroom Program will be eligible for Rank, Special Gift and Memento through VE-GRE. Students will not be Eligible for Assured Cash Reward, Cash Reward (on Admission), Cash Reward (after Admission), Scholarship, Hostel Fee Benefits and Fooding Fee Benefits offered through VE-GRE.",
  // "Students presently studying in Class 8th, 9th & 10th and already Enrolled in Vertex Educations in 5 year/ 4 year/ 3 year Integrated Regular Classroom Program will be Eligible for Rank, Special Gift and Memento through VE-GRE. Students will not be Eligible for Assured Cash Reward, Cash Reward (on Admission), Cash Reward (after Admission), Scholarship, Hostel Fee Benefits and Fooding Fee Benefits offered through VE-GRE.",
  // "Students presently studying in Class 8th, 9th & 10th and Not Enrolled in Vertex Educations in 5 year/ 4 year/ 3 year Integrated Regular Classroom Program will be Eligible for all the Benefits offered through VE-GRE i.e., Assured Cash Reward, Cash Reward (on Admission), Cash Reward (after Admission), Scholarship, Hostel Fee Benefits and Fooding Fee Benefits.",
  // "The Scholarship will be offered to these students based on performance of student in VE-GRE and also performance of student in all the Mentors Internal tests (conducted till date).",
  // "22.   (a) The registered office of Vertex Educations is at Patna. All disputes and differences of any nature with regard to subsequent enrollments and studies shall be resolved through process of arbitration. Appointment of sole arbitrator will take place through mutual consent of both the parties failing which such appointment shall be made by Arbitral Institution designated by Patna High Court. The arbitration proceeding shall be conducted in accordance with the provision of the Arbitration and Conciliation Act 1996 and statutory modification thereof and rules made there under. The award of the arbitrator shall be binding and final.",
  // "         (b) Subject to 23(a) herein above, the exclusive jurisdiction in the matter shall vest in Patna Court only.",
  // "NOTE:     ",
  // "1.     Total reward amount mentioned (on page 6,7 & 8) is for 7 year integrated program (for class 6 going students), 6 year integrated program (for class 7 going students), 5 year integrated program (for class 8 going students), 4 year integrated program (for class 9 going students), 3 year integrated program (for class 10 going students) and  2 year  program (for class 11 going students).",
  // "2.     Total reward amount is the sum of assured cash reward, scholarship amount, maximum cash reward on admission, maximum cash reward after admission, monthly hostel fee benefit and monthly fooding fee benefit.",
  // "3.     Reward after taking Admission will be awarded to students based on performance in the internal tests (will be conducted in Offline mode or Computer based Test mode).",
  // "",
];

export const sruopklpkll = "Strix Digital";
